[book]
authors = ["tomeichlersmith"]
language = "en"
multilingual = false
src = "src"
title = "denv"

[output.html]
mathjax-support = true
site-url = "/denv/"
git-repository-url = "https://github.com/tomeichlersmith/denv/tree/main/"
edit-url-template = "https://github.com/tomeichlersmith/denv/edit/main/docs/{path}"

[preprocessor.man-to-html]
command = "python3 man-to-html.py"
